pipelines:
  branches:
    production:
      - step:
          name: Sync GitHub Mirror
          image: alpine/git:latest
          clone:
            enabled: false
          script:
            - git clone --bare git@bitbucket.org:Shahar0080/discord-travel-budget-tracker.git
            - cd discord-travel-budget-tracker.git
            - git push --mirror git@github.com:shahar080/discord-travel-budget-tracker.git
